shields: adafruit_2_8_tft_touch_v2: add arduino nano connector support
brgl/zephyr pull request #1
Opened 2022-03-29 09:16 UTC by jfischer-no

Allow shield to be used with any board that has an
arduino nano connector.

2022-04-05 12:07 UTC, brgl commented
@jfischer-no gentle ping on my question

2022-04-05 12:23 UTC, jfischer-no commented
> @jfischer-no gentle ping on my question

What question or where?

2022-04-05 13:03 UTC, brgl commented
![image](https://user-images.githubusercontent.com/3023613/161759713-09e414a2-35ff-45d7-a214-ccadc640f013.png)

@jfischer-no are you not seeing this review?

2022-04-05 13:43 UTC, jfischer-no commented
>@jfischer-no are you not seeing this review?

Nope, and according to your screenshot, it is still pending.

2022-04-05 13:46 UTC, brgl requested changes

2022-04-05 13:46 UTC, brgl commented on boards/shields/adafruit_2_8_tft_touch_v2/adafruit_2_8_tft_touch_v2_nano.overlay
> +			   <16 0 &arduino_nano_header 9 0>;  /* D9  */
I understand the logic behind this commit but I wonder how stable that HW interface is? It looks like the pins on the nano header can be used differently depending on the board. For instance: looking at the Nano IoT DT I'm seeing that the RX and TX pins seem to be inverted compared to BLE? Are we sure those GPIOs that are mapped here will be the same on all boards?

2022-04-05 13:47 UTC, brgl commented
> > @jfischer-no are you not seeing this review?
> 
> Nope, and according to your screenshot, it is still pending.

Duh... Sorry for that -ETOOTIRED

2022-04-05 14:11 UTC, jfischer-no commented on boards/shields/adafruit_2_8_tft_touch_v2/adafruit_2_8_tft_touch_v2_nano.overlay
> +			   <16 0 &arduino_nano_header 9 0>;  /* D9  */
> looking at the Nano IoT DT I'm seeing that the RX and TX pins seem to be inverted compared to BLE? Are we sure those GPIOs that are mapped here will be the same on all boards?

That is the reason to have arduino_nano_header (same as arduino_header), it must be stable, if these pins are different then it is a problem with the board, or it does not have an arduino_nano connector.

2022-04-05 14:14 UTC, jfischer-no commented on boards/shields/adafruit_2_8_tft_touch_v2/adafruit_2_8_tft_touch_v2_nano.overlay
> +			   <16 0 &arduino_nano_header 9 0>;  /* D9  */
![NANO IOT](https://content.arduino.cc/assets/Pinout-NANO33IoT_latest.png)
![NANO BLE](https://content.arduino.cc/assets/Pinout-NANOble_latest.png)

2022-04-05 14:19 UTC, brgl commented on boards/shields/adafruit_2_8_tft_touch_v2/adafruit_2_8_tft_touch_v2_nano.overlay
> +			   <16 0 &arduino_nano_header 9 0>;  /* D9  */
So I take it that the following snippet from `boards/arm/arduino_nano_33_iot/arduino_nano_r3_connector.dtsi` is a bug?

```
 12                 gpio-map = <0 0 &portb 23 0>,  /* D0 / UART-RX */
 13                            <1 0 &portb 22 0>,  /* D1 / UART-TX */
```

2022-04-06 09:03 UTC, brgl commented on boards/shields/adafruit_2_8_tft_touch_v2/adafruit_2_8_tft_touch_v2_nano.overlay
> +			   <16 0 &arduino_nano_header 9 0>;  /* D9  */
Ok this isn't relevant for this PR anyway, I'll open up a different thread.

2022-04-06 09:08 UTC, merged